### PR TITLE
[Android] Fix unused kTestEmail in VPN v2 service unittest

### LINKED ISSUE #58249: [VPN 2.0] Android build fails: unused variable 'kTestEmail' in brave_vpn_service_impl_unittest.cc
The Android build of `brave_components_unittests` fails with:

```
../../brave/components/brave_vpn/browser/v2/brave_vpn_service_impl_unittest.cc:37:16: error: unused variable 'kTestEmail' [-Werror,-Wunused-const-variable]
   37 | constexpr char kTestEmail[] = "test@example.com";

`kTestEmail` is only referenced inside the `#if !BUILDFLAG(IS_ANDROID)` block that
exercises `CreateSupportTicket()`, so on Android the constant is unused and
`-Wunused-const-variable` (with `-Werror`) breaks the build.
```

Introduced in [brave/brave-core#39162](https://github.com/brave/brave-core/pull/39162).

### PR DESCRIPTION
**Pull request by SergeyZhukovsky**
`kTestEmail` is only used inside the !IS_ANDROID block covering `CreateSupportTicket()`, so Android failed with `-Wunused-const-variable`. Introduced in https://github.com/brave/brave-core/pull/39162

Resolves: https://github.com/brave/brave-browser/issues/58249

### CODE REVIEW

**Comment by SergeyZhukovsky** [comment]
Merging to unblock master
