### PR TITLE
Fix errors in os_crypt patch files for Linux

### PR DESCRIPTION
**Pull request by garrettr**
Fixes Linux compilation errors that were introduced in #77.

## Submitter Checklist:

- [ ] Submitted a [ticket](https://github.com/brave/brave-browser/issues) for my issue if one did not already exist.
- [ ] Used Github [auto-closing keywords](https://help.github.com/articles/closing-issues-via-commit-messages/) in the commit message.
- [ ] Added/updated tests for this change (for new code or code which already has tests).
- [ ] Ran `git rebase -i` to squash commits (if needed).
- [x] Tagged reviewers and labelled the pull request as needed.
- [ ] Request a security/privacy review as needed.

## Test Plan:

1. Checkout this branch and run `yarn run sync --run_hooks` to apply the updated patches.
2. Build on Linux. The build should complete without errors.

## Reviewer Checklist:

- [ ] New files have MPL-2.0 license header.
- [ ] Request a security/privacy review as needed.
- [ ] Adequate test coverage exists to prevent regressions

### CODE REVIEW

**Comment by garrettr** [comment]
These changes fix the build in my Ubuntu 16.04 VM. I ran into a confusing compilation error caused by sccache while working on this, but am going to file a separate issue for that since use of sccache is optional.

@AlexeyBarabash Could you confirm that this PR fixes your Linux builds?

**Comment by simonhong** [comment]
With this PR, I can build and run brave on linux(ubuntu 16.04).
