### PR TITLE
[Storybook]: Upgrade to version 8

### PR DESCRIPTION
**Pull request by fallaciousreasoning**
Resolves https://github.com/brave/brave-browser/issues/39181

**Upgrade Notes:**
- `@storybook/manager-api` replaces our usages of `@storybook/addons`. https://github.com/storybookjs/storybook/blob/next/MIGRATION.md#new-addons-api
- Latest version of `storybook` is 8.1.3, but `@storybook/addon-knobs` only has a `8.0.1` release, so I've bumped to that instead.

## Submitter Checklist:

- [ ] I confirm that no [security/privacy review is needed](https://github.com/brave/brave-browser/wiki/Security-reviews) and no other type of reviews are needed, or that I have [requested](https://github.com/brave/reviews/issues/new/choose) them
- [ ] There is a [ticket](https://github.com/brave/brave-browser/issues) for my issue
- [ ] Used Github [auto-closing keywords](https://docs.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue) in the PR description above
- [ ] Wrote a good [PR/commit description](https://google.github.io/eng-practices/review/developer/cl-descriptions.html)
- [ ] Squashed any review feedback or "fixup" commits before merge, so that history is a record of what happened in the repo, not your PR
- [ ] Added appropriate labels (`QA/Yes` or `QA/No`; `release-notes/include` or `release-notes/exclude`; `OS/...`) to the associated issue
- [ ] Checked the PR locally:
  * `npm run test -- brave_browser_tests`, `npm run test -- brave_unit_tests` [wiki](https://github.com/brave/brave-browser/wiki/Tests)
  * `npm run presubmit` [wiki](https://github.com/brave/brave-browser/wiki/Presubmit-checks), `npm run gn_check`, `npm run tslint`
- [ ] Ran `git rebase master` (if needed)

## Reviewer Checklist:

- [ ] A security review [is not needed](https://github.com/brave/brave-browser/wiki/Security-reviews), or a link to one is included in the PR description
- [ ] New files have MPL-2.0 license header
- [ ] Adequate test coverage exists to prevent regressions
- [ ] Major classes, functions and non-trivial code blocks are well-commented
- [ ] Changes in component dependencies are properly reflected in `gn`
- [ ] Code follows the [style guide](https://chromium.googlesource.com/chromium/src/+/HEAD/styleguide/c++/c++.md)
- [ ] Test plan is specified in PR before merging

## After-merge Checklist:

- [ ] The associated issue milestone is set to the smallest version that the
  changes has landed on
- [ ] All relevant documentation has been updated, for instance:
  - [ ] https://github.com/brave/brave-browser/wiki/Deviations-from-Chromium-(features-we-disable-or-remove)
  - [ ] https://github.com/brave/brave-browser/wiki/Proxy-redirected-URLs
  - [ ] https://github.com/brave/brave-browser/wiki/Fingerprinting-Protections
  - [ ] https://github.com/brave/brave-browser/wiki/Brave%E2%80%99s-Use-of-Referral-Codes
  - [ ] https://github.com/brave/brave-browser/wiki/Web-Compatibility-Exceptions-in-Brave
  - [ ] https://github.com/brave/brave-browser/wiki/QA-Guide
  - [ ] https://github.com/brave/brave-browser/wiki/P3A

## Test Plan:

N/A this is a developer facing dependency bump

### CODE REVIEW

**Review by diracdeltas — APPROVED** [review]
LGTM, audit-deps is failing due to the dalek issue which will be fixed with https://github.com/brave/brave-core/pull/24287

File: components/ai_chat/resources/page/components/markdown_renderer/index.tsx [hunk 1]
```diff
@@ -7,7 +7,7 @@ import * as React from 'react'
 import Markdown from 'react-markdown'
 import type { Root, Element as HastElement } from 'hast'
 
-const visit = require('unist-util-visit/index')
+const visit = require('unist-util-visit')
```
Comment (nullhook) [inline components/ai_chat/resources/page/components/markdown_renderer/index.tsx:10]: getting a runtime crash

```
[83686:259:0625/113856.891284:ERROR:CONSOLE(33572)] "Uncaught TypeError: visit is not a function", source: chrome-untrusted://chat/chat_ui.bundle.js (33572)
```

Comment (petemill) [reply components/ai_chat/resources/page/components/markdown_renderer/index.tsx:10]: If so, that means we don't have a single browser test which runs the AI Chat webui

Comment (petemill) [reply components/ai_chat/resources/page/components/markdown_renderer/index.tsx:10]: Preparing a revert in case this isn't a simple fix https://github.com/brave/brave-core/pull/24373

Comment (fallaciousreasoning) [reply components/ai_chat/resources/page/components/markdown_renderer/index.tsx:10]: Does turning just this line fix it @nullhook? It's interesting, because this works in the storybook

Comment (fallaciousreasoning) [reply components/ai_chat/resources/page/components/markdown_renderer/index.tsx:10]: Its extremely weird that theres a difference between `/dir` and `/dir/index` as they should both import `index`

Comment (fallaciousreasoning) [reply components/ai_chat/resources/page/components/markdown_renderer/index.tsx:10]: Sorry @nullhook
