### PR TITLE
Fix possible merge issue for some rewards code in 0.57.x

### PR DESCRIPTION
**Pull request by bsclifton**
Verified import functionality works as expected

Fixes https://github.com/brave/brave-browser/issues/2287

## Submitter Checklist:

- [x] Submitted a [ticket](https://github.com/brave/brave-browser/issues) for my issue if one did not already exist.
- [x] Used Github [auto-closing keywords](https://help.github.com/articles/closing-issues-via-commit-messages/) in the commit message.
- [ ] Added/updated tests for this change (for new code or code which already has tests).
- Verified that these changes build without errors on
  - [ ] Windows
  - [x] macOS
  - [ ] Linux
- Verified that these changes pass automated tests (`npm test brave_unit_tests && npm test brave_browser_tests`) on
  - [ ] Windows
  - [ ] macOS
  - [ ] Linux
- [x] Ran `git rebase master` (if needed).
- [x] Ran `git rebase -i` to squash commits (if needed).
- [x] Tagged reviewers and labelled the pull request as needed.
- [ ] Request a security/privacy review as needed.
- [x] Add appropriate QA labels (QA/Yes or QA/No) to include the closed issue in milestone

## Reviewer Checklist:

- [ ] New files have MPL-2.0 license header.
- [ ] Request a security/privacy review as needed.
- [ ] Adequate test coverage exists to prevent regressions 
- [ ] Verify test plan is specified in PR before merging to source

### CODE REVIEW

File: components/brave_rewards/browser/rewards_service_observer.h [hunk 1]
```diff
@@ -6,7 +6,9 @@
 #define BRAVE_BROWSER_PAYMENTS_PAYMENTS_SERVICE_OBSERVER_H_
 
 #include "brave/components/brave_rewards/browser/wallet_properties.h"
```
Comment (mkarolin) [inline components/brave_rewards/browser/rewards_service_observer.h]: origin/master also includes `#include "base/observer_list_types.h"` for base::CheckedObserver.

Comment (bsclifton) [reply components/brave_rewards/browser/rewards_service_observer.h]: Fixed! (it still compiled and worked without that?)

**Comment by bsclifton** [comment]
browser test compilation is failing with this (caused by https://github.com/brave/brave-core/pull/924 uplift):
```
In file included from ../../brave/browser/themes/brave_theme_service_browsertest.cc:14:
In file included from ../../testing/gmock/include/gmock/gmock.h:10:
../../third_party/googletest/src/googlemock/include/gmock/gmock.h:59:10: fatal error: 'gmock/gmock-actions.h' file not found
```
